name: Surge Sphinx deployment
on: [push, pull_request]

jobs:
  build:
    name: Surge Sphinx action
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@master
    - uses: .
      env:
        BUILD_DIR: $(echo $pwd '/_build')
